name: Release

# on events
on:
  push:
    tags:
      - v*

permissions:
  contents: write

# workflow tasks
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git LFS
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - run: git lfs pull

      - name: Fetch all tags
        run: git fetch --force --tags

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ~/.cache
          key: livekit-cli

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
